en:
  farewell_message: "Bye! I'll miss you :("
  greeting_message: "OpenAI is awesome! You may ask anything to me (:"
  help_message : |
    Welcome to OpenAI Bot!

    This bot allows you to interact with OpenAI's GPT-3 model through a chat interface. Here are the available commands you can use:
    1. /start - This command starts the bot and allows you to begin chatting with the GPT-3 model. Simply type your message after using this command to start the conversation.
    2. /stop - This command stops the bot and ends the current conversation with the GPT-3 model. Use this command when you want to stop chatting and exit the bot.
    3. /help - This command provides you with information about the available commands and how to use the bot. If you ever need assistance or have questions about the bot, use this command to get help.

    To use the bot, simply type one of the available commands, then type your message to interact with the GPT-3 model. Feel free to start a conversation, ask questions, or engage in any type of dialogue you'd like!
    If you have any further questions or need additional assistance, please don't hesitate to reach out by using the /help command. Enjoy chatting with OpenAI Bot!
